- hosts: localhost
  connection: local
  gather_facts: no           
  vars:
    homebrew_taps:
      - fisherman/tap
      - caskroom/cask
      - caskroom/fonts
    homebrew_packages:
      - { name: fish }
      - { name: fisherman }
      - { name: fzy }
      - { name: go }
      - { name: gibo }
      - { name: pyenv-virtualenv }
      - { name: ripgrep }
      - { name: aria2, install_options: with-libssh2 }
      - { name: terminal-notifier }
    homebrew_cask_packages:
      - { name: alfred }
      - { name: bartender }
      - { name: vivaldi }
      - { name: flash-ppapi }
      - { name: hyperswitch }
      - { name: tomighty }
      - { name: iterm2 }
      - { name: slack }
      - { name: discord }
      - { name: visual-studio-code }
      - { name: dropbox }
      - { name: 1password }
      - { name: font-hasklig-nerd-font }
      - { name: font-source-han-code-jp }
    go_get_list:
      - github.com/motemen/ghq

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: "{{ homebrew_taps }}"

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: "{{ homebrew_packages }}"

    # cask
    - name: cask パッケージをインストール
      environment:
        HOMEBREW_CASK_OPTS=: --appdir=~/Applications
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: "{{ homebrew_cask_packages }}"

    - name: go go_get_list
      command: go get -u {{ item }}
      with_items: "{{ go_get_list }}"
