- hosts: localhost
  connection: local
  gather_facts: no           
  vars:
    homebrew_taps:
      - fisherman/tap
      - caskroom/cask
      - caskroom/fonts
    homebrew_packages:
      - { name: fish }
      - { name: fisherman }
      - { name: go }
      - { name: gibo }
      - { name: terminal-notifier }
      - { name: tmux }
      - { name: reattach-to-user-namespace }
      - { name: tig }
      - { name: pipenv }
      - { name: python }
      - { name: python3 }
      - { name: htop }
      - { name: vim, install_options: ["with-gettext", "with-luajit", "with-python3", "with-tcl"]}
    homebrew_cask_packages:
      - { name: hyperswitch }
      - { name: slack }
      - { name: visual-studio-code }
      - { name: firefox }
      - { name: dropbox }
      - { name: caffeine }
      - { name: font-cica }
      - { name: iterm2 }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: "{{ homebrew_taps }}"

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: "{{ homebrew_packages }}"

    # cask
    - name: cask パッケージをインストール
      environment:
        HOMEBREW_CASK_OPTS: --appdir=~/Applications
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: "{{ homebrew_cask_packages }}"
