- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "../vars/dotfiles.yml"
  vars:
    HOME: "{{ lookup('env', 'HOME') }}"
    repository_dir: "{{ '%s/.ghq/%s' | format(HOME, repository) }}"
  tasks:
    - name: "mkdir -p {{ repository_dir | dirname }}"
      file:
        path: "{{ repository_dir | dirname }}"
        state: directory
        recurse: yes

    - name: dotfiles repository を clone
      git:
        repo: "https://{{ repository }}.git"
        dest: "{{ repository_dir }}"

    - name: dotfiles の symlink を 作成
      shell: "$(go env GOPATH)/bin/rlink -i '.git/' {{ repository_dir }} {{ HOME }}"

