- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "../vars/mygtc.yml"

  tasks:
    - name: install golang
      homebrew:
        name: go

    - name: build mygtc
      shell: go install
      args: 
        chdir: ../mygtc

    - name: install softwares
      shell: $(go env GOPATH)/bin/mygtc install {{ item }}
      with_items: "{{ mygtc_items }}"

    - name: update softwares
      shell: $(go env GOPATH)/bin/mygtc update
      register: result
      failed_when: result.rc not in [0, 1]
