- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "../vars/tap.yml"

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: "{{ homebrew_taps }}"

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    - name: enable homebrew auto-update
      shell: brew autoupdate --start --upgrade --cleanup --enable-notification
      register: result
      failed_when: false

    - name: terminfo-24bit.src の準備
      copy:
        src: terminfo-24bit.src
        dest: /tmp/terminfo-24bit.src

    - name: terminfo のコンパイル
      shell: tic -x -o /usr/share/terminfo /tmp/terminfo-24bit.src
